# Vectors and Matrices in Numpy - Lab

## Introduction

In this lab, you'll solve some simple matrix creation and manipulation exercises based on what you've learned so far in this section. The key takeaway here is to be able to understand how to use indexing with matrices and vectors while applying some basic operations.

## Objectives

In this lab you will: 

- Find the shape of vectors and matrices 
- Access and manipulate individual scalar components of a matrix 
- Create vectors and matrices using Numpy and Python

## 1. Define two arrays $A$  with shape $ (4 \times 2)$ and $B$ with shape $(2 \times 3)$ 
So    $A =    
  \left[ {\begin{array}{cc}
   1402 & 191 \\
   1371 &  821\\
   949 &  1437 \\
   147 & 1448 \\
  \end{array} }\right]
$
and
$
B =    
  \left[ {\begin{array}{ccc}
   1 & 2 & 3 \\
   4 & 5 & 6\\
  \end{array} }\right]
$

In [1]:
import numpy as np

In [5]:
# Code here
A = np.array([[1402, 191],[1371, 821],[949, 1437],[147, 1448]])
B = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print(B)

[[1402  191]
 [1371  821]
 [ 949 1437]
 [ 147 1448]]
[[1 2 3]
 [4 5 6]]


## 2. Print the dimensions of $A$ and $B$ 

In [7]:
# Code here
print(A.shape)
print(B.shape)

(4, 2)
(2, 3)


## 3. Print elements from $A$

Print the following elements from $A$: 

* First row and first column
* First row and second column
* Third row and second column
* Fourth row and first column

In [13]:
# Code here
print(A)
print('First row and first column:', A[0,0])
print('First row and second column:', A[0,1])
print('Third row and second column:', A[2,1])
print('Fourth row and first column:', A[-1,0])

[[1402  191]
 [1371  821]
 [ 949 1437]
 [ 147 1448]]
First row and first column: 1402
First row and second column: 191
Third row and second column: 1437
Fourth row and first column: 147


## 4. Write a routine to populate a matrix with random data
* Create an $(3 \times 3)$ Numpy array with all zeros (use `np.zeros()`)
* Access each location $(i,j)$ of this matrix and fill in random values between the range 1 and 10 

In [1]:
# Code here
# Create my array
import numpy as np
M = np.zeros([3, 3])
M

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# Check if assigning random works
import random 
M[0,0] = random.randint(1, 10)
M

array([[5., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
M.shape[0]

3

In [21]:
# Yeah, I think it worked
import random
i = 0
j = 0
while i < M.shape[0]:
    M[i, j] = random.randint(1, 10)
    i = i+1
    if(i == M.shape[0]):
        i = 0
        j = j+1
        if(j == M.shape[1]):
            break
print(M)


[[ 8.  1. 10.]
 [ 1. 10.  2.]
 [ 9.  6. 10.]]


## 5. Turn the above routine into a function
* Create two $(4 \times 4)$ zero-valued matrices and fill with random data using the function
* Add the matrices together in Numpy 
* Print the results

In [22]:
import random

def matrix_maker(a, b):
    M = np.zeros([a, b])
    i = 0
    j = 0
    while i < M.shape[0]:
        M[i, j] = random.randint(1, 10)
        i = i+1
        if(i == M.shape[0]):
            i = 0
            j = j+1
            if(j == M.shape[1]):
                break
    return(M)

In [32]:
# Code here
A = matrix_maker(4, 4)
B = matrix_maker(4, 4)
C = A + B
print('Matrix A:', '\n', A, '\n')
print('Matrix B:', '\n', B, '\n')
print('Matrix C:', '\n', C)

Matrix A: 
 [[ 2.  9.  9. 10.]
 [ 6. 10.  4.  1.]
 [ 4.  8.  7.  9.]
 [ 1.  8.  5.  3.]] 

Matrix B: 
 [[ 3.  9.  2.  2.]
 [ 1.  9.  1.  2.]
 [ 8.  9.  6.  1.]
 [ 4.  1.  8. 10.]] 

Matrix C: 
 [[ 5. 18. 11. 12.]
 [ 7. 19.  5.  3.]
 [12. 17. 13. 10.]
 [ 5.  9. 13. 13.]]


## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in Numpy. We shall now move forward to learning more complex operations including dot products and matrix inversions.  

In [ ]:
# Their code

In [33]:
import random
M = np.zeros((3, 3))
print ('before random data:\n',M)

for x in range(0, M.shape[0]):
    for y in range(0, M.shape[1]):
        M[x][y] = random.randrange(1, 10) 
print ('\nafter random data:\n',M)

before random data:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

after random data:
 [[6. 4. 6.]
 [2. 1. 5.]
 [7. 5. 4.]]


In [37]:
def fill(matrix):

    for x in range(0, matrix.shape[0]):
        for y in range(0, matrix.shape[1]):
            matrix[x][y] = random.randrange(1, 10)
    
    return matrix

M1 = np.zeros((4, 4))
M2 = np.zeros((4, 4))

M1_filled = fill(M1)
M2_filled = fill(M2)
out = M1_filled + M2_filled

print(M1_filled, '\n')
print(M2_filled, '\n')
print ('Final output\n\n', out)

[[5. 2. 5. 9.]
 [4. 5. 4. 8.]
 [4. 4. 3. 9.]
 [1. 7. 9. 3.]] 

[[4. 9. 2. 1.]
 [3. 5. 1. 7.]
 [8. 4. 6. 7.]
 [7. 9. 1. 1.]] 

Final output

 [[ 9. 11.  7. 10.]
 [ 7. 10.  5. 15.]
 [12.  8.  9. 16.]
 [ 8. 16. 10.  4.]]
